version: '3.9'

services:
  db: 
    container_name: "db_postgres"
    restart: allways
    image: postgres:latest
    ports:
      - 5436:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
volumes:
  db_data: