services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./bun.lockb
          action: rebuild
        - path: ./
          target: /app
          action: sync
