apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
    name: backend-ingress
    namespace: messenger-clone
spec:
    ingressClassName: traefik
    rules:
        - host: messenger-clone-backend.mikolajmaciejak.dev
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: backend
                            port:
                                number: 4000
    tls:
        - hosts:
              - messenger-clone-backend.mikolajmaciejak.dev
          secretName: mikolajmaciejak-dev-cert-tls
