apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        io.kompose.service: db-claim0
    name: db-claim0
    namespace: messenger-clone
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 150Mi
